### ISSUE TITLE
Provide Auto Merge information in pull request?

### ISSUE THREAD

**Issue by jeskosda** [hub4j/github-api#1245]
Hey all ✋🏻 ,

unfortunately, it's not possible to enable the auto merge via the https://docs.github.com/en/rest/reference/pulls API.
But for a current project, I need at least the auto merge information about a `GHPullRequest`. 

I prepared a suggestion, but since it would be my first contribution, I just want to hear your opinion about  adding the information to the `GHPullRequest`. I made a suggestion here:
https://github.com/jeskosda/github-api/commit/7622293b2e4731019a20c3098a0b93347f276aa6

Since it's hard to prepare the auto merge in the test, I extended a current snapshot.

**Comment by bitwiseman** [comment]
Where did you find the details of the json information returned for `auto_merge`?  Via the API or is it documented somewhere?

**Comment by bitwiseman** [comment]
That commit looks pretty good.  I provided some feedback/questions.

**Comment by jeskosda** [comment]
Thanks! I checked that via the OpenAPI definition, but double-checked this with a request against the API.

```yaml
auto_merge:
      title: Auto merge
      description: The status of auto merging a pull request.
      type: object
      properties:
        enabled_by:
          "$ref": "#/components/schemas/simple-user"
        merge_method:
          type: string
          description: The merge method to use.
          enum:
            - merge
            - squash
            - rebase
        commit_title:
          type: string
          description: Title for the merge commit message.
        commit_message:
          type: string
          description: Commit message for the merge commit.
      required:
        - enabled_by
        - merge_method
        - commit_title
        - commit_message
      nullable: true
```

Thanks for the feedback, I'll create a PR with the suggested changes!
